export const languages = {
    en: {
        nativeName: "English",
        title: "Debate Planner",
        opd_house: "House",
        opd_opposition: "Opposition",
        opd_free_speakers: "Free Speakers",
        bpd_house_1: "Opening Government",
        bpd_house_2: "Closing Government",
        bpd_opposition_1: "Opening Opposition",
        bpd_opposition_2: "Closing Opposition",
        jury: "Jury",
        unsorted: "Unsorted",
        name_placeholder: "Name",
        tooltipToggleNew: "Member Inexperienced?",
        tooltipAddMember: "Add Member",
        btn_add_room: "Create room",
        btn_move_room_up: "Move room up",
        btn_move_room_down: "Move room down",
        opd: "Open Parliamentary Debate",
        bpd: "British Parliamentary Style",
        opd_compact: "OPD",
        bpd_compact: "BPS",
        tooltipRetrieve: "Retrieve",
        tooltipDistribute: "Distribute",
        tooltipDistributeSlots: "Distribute to groups",
        tooltipDistributeRooms: "Distribute to rooms",
        room_name_placeholder: "Room ",
        label_group_size: "Group Size",
        label_debate_style: "Debate Style",
    },
    de: {
        nativeName: "Deutsch",
        title: "Debattenplaner",
        opd_house: "Regierung",
        opd_opposition: "Opposition",
        opd_free_speakers: "Freie Sprecher",
        bpd_house_1: "Eröffnende Regierung",
        bpd_house_2: "Schließende Regierung",
        bpd_opposition_1: "Eröffnende Opposition",
        bpd_opposition_2: "Schließende Opposition",
        jury: "Jury",
        unsorted: "Unsortiert",
        name_placeholder: "Name",
        tooltipToggleNew: "Mitglied Unerfahren?",
        tooltipAddMember: "Mitglied Hinzufügen",
        btn_add_room: "Raum Erstellen",
        btn_move_room_up: "Raum nach oben verschieben",
        btn_move_room_down: "Raum nach unten verschieben",
        opd: "Offene Parlamentarische Debatte",
        bpd: "British Parliamentary Style",
        opd_compact: "OPD",
        bpd_compact: "BPS",
        tooltipRetrieve: "Sammeln",
        tooltipDistribute: "Verteilen",
        tooltipDistributeSlots: "An Gruppen verteilen",
        tooltipDistributeRooms: "An Räume verteilen",
        room_name_placeholder: "Raum ",
        label_group_size: "Gruppengröße",
        label_debate_style: "Debattenstil",
    },
} as const satisfies Record<string, Record<string, string>>